// <auto-generated />
namespace JapaneseBook.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712251640023_remove-user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
